/*
 * atest.h
 *
 *  Created on: 4 mar. 2019
 *      Author: user
 */

#ifndef SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_ULTRASONICSENSORS_ULTRASONICSENSOR_HCSR04_01_SRC_ATEST_H_
#define SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_ULTRASONICSENSORS_ULTRASONICSENSOR_HCSR04_01_SRC_ATEST_H_


bool_t evalTest(uint32_t pdst, uint32_t accepted);


#endif /* SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_ULTRASONICSENSORS_ULTRASONICSENSOR_HCSR04_01_SRC_ATEST_H_ */
