/*
 * dst_cm.h
 *
 *  Created on: 6 mar. 2019
 *      Author: user
 */

#ifndef SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_ULTRASONICSENSORS_ULTRASONICSENSOR_HCSR04_01_SRC_DST_CM_H_
#define SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_ULTRASONICSENSORS_ULTRASONICSENSOR_HCSR04_01_SRC_DST_CM_H_

float distanceCM(float pdst);



#endif /* SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_ULTRASONICSENSORS_ULTRASONICSENSOR_HCSR04_01_SRC_DST_CM_H_ */
