/*
 * dst_mm_xdef.h
 *
 *  Created on: 6 mar. 2019
 *      Author: user
 */

#ifndef SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_ULTRASONICSENSORS_ULTRASONICSENSOR_HCSR04_01_SRC_DST_MM_XDEF_H_
#define SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_ULTRASONICSENSORS_ULTRASONICSENSOR_HCSR04_01_SRC_DST_MM_XDEF_H_



float distanceMMxdef(float pdst);

#endif /* SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_ULTRASONICSENSORS_ULTRASONICSENSOR_HCSR04_01_SRC_DST_MM_XDEF_H_ */
